-- Blankeos Zen Dark (Blurred) for Neovim.
-- AI-maintained local colorscheme.
-- Based on: /Users/carlo/Desktop/Projects/zen.zed/themes/blankeos-zen-dark-blurred.json
-- Source project: /Users/carlo/Desktop/Projects/zen.zed

vim.cmd("highlight clear")

if vim.fn.exists("syntax_on") == 1 then
  vim.cmd("syntax reset")
end

vim.o.background = "dark"
vim.o.termguicolors = true
vim.g.colors_name = "blankeos-zen-dark-blurred"

local p = {
  none = "NONE",

  bg = "#121212",
  bg_surface = "#19191a",
  bg_overlay = "#0b0b0b",
  bg_overlay_hover = "#101010",
  bg_tab_inactive = "#1b1b1b",
  bg_tab_active = "#23252b",
  bg_active_line = "#1f1f21",
  bg_active_line_soft = "#1a1a1c",
  bg_menu_selection = "#242426",
  bg_document_highlight = "#202023",
  bg_bracket = "#1b2730",
  bg_search = "#343b46",
  bg_incsearch = "#60a5fa",
  bg_selection = "#314d6f",
  bg_diff_add = "#143128",
  bg_diff_change = "#26303a",
  bg_diff_delete = "#35181d",
  bg_error = "#590a0f",
  bg_warning = "#312f20",
  bg_info = "#22313d",
  bg_hint = "#242424",

  border = "#2a2a2d",
  border_dim = "#202022",

  text = "#a6accd",
  text_muted = "#767c9d",
  text_dim = "#606586",
  text_predictive = "#515671",
  text_strong = "#e4f0fb",
  white = "#ffffff",

  primary = "#60a5fa",
  cursor = "#bae6fd",
  blue = "#60a5fa",
  blue_bright = "#add7ff",
  blue_terminal = "#89ddff",
  blue_soft = "#91b4d5",
  green = "#5de4c7",
  green_soft = "#5fb3a1",
  yellow = "#fffac2",
  yellow_soft = "#eed49f",
  orange = "#f2803a",
  red = "#d0679d",
  red_bright = "#e84c5a",
  magenta = "#f087bd",
  purple = "#c77bd2",
  violet = "#a855f7",
  hint = "#969696",
}

local transparent = vim.g.blankeos_zen_dark_blurred_transparent ~= false
local normal_bg = transparent and p.none or p.bg

local function hl(group, spec)
  vim.api.nvim_set_hl(0, group, spec)
end

local groups = {
  -- Editor base --------------------------------------------------------------
  Normal = { fg = p.text, bg = normal_bg },
  NormalNC = { fg = p.text, bg = normal_bg },
  NormalFloat = { fg = p.text, bg = p.bg },
  FloatBorder = { fg = p.border, bg = p.bg },
  FloatTitle = { fg = p.blue_bright, bg = p.bg },
  FloatFooter = { fg = p.text_muted, bg = p.bg },
  EndOfBuffer = { fg = transparent and p.bg or p.bg_surface, bg = normal_bg },
  FoldColumn = { fg = p.text_dim, bg = normal_bg },
  SignColumn = { fg = p.text_dim, bg = normal_bg },
  LineNr = { fg = p.text_muted, bg = normal_bg },
  LineNrAbove = { fg = p.text_dim, bg = normal_bg },
  LineNrBelow = { fg = p.text_dim, bg = normal_bg },
  CursorLine = { bg = p.bg_active_line },
  CursorColumn = { bg = p.bg_active_line },
  CursorLineNr = { fg = p.primary, bg = p.bg_active_line },
  CursorLineFold = { fg = p.text_muted, bg = p.bg_active_line },
  CursorLineSign = { fg = p.text_muted, bg = p.bg_active_line },
  ColorColumn = { bg = p.bg_active_line_soft },
  Conceal = { fg = p.text_muted, bg = normal_bg },
  Cursor = { fg = p.bg, bg = p.cursor },
  lCursor = { fg = p.bg, bg = p.cursor },
  CursorIM = { fg = p.bg, bg = p.cursor },
  Directory = { fg = p.primary },
  WinSeparator = { fg = p.border_dim, bg = normal_bg },
  VertSplit = { fg = p.border_dim, bg = normal_bg },
  Folded = { fg = p.text_muted, bg = p.bg_surface },
  NonText = { fg = p.text_dim },
  SpecialKey = { fg = p.text_dim },
  Whitespace = { fg = p.text_dim },
  Question = { fg = p.primary },
  MoreMsg = { fg = p.green },
  ModeMsg = { fg = p.text },
  ErrorMsg = { fg = p.red },
  WarningMsg = { fg = p.yellow },
  Title = { fg = p.blue_soft },
  Visual = { bg = p.bg_selection },
  VisualNOS = { bg = p.bg_selection },
  Search = { fg = p.text_strong, bg = p.bg_search },
  IncSearch = { fg = p.bg, bg = p.bg_incsearch },
  CurSearch = { fg = p.bg, bg = p.bg_incsearch },
  Substitute = { fg = p.bg, bg = p.red },
  MatchParen = { fg = p.blue_bright, bg = p.bg_bracket, bold = true },
  QuickFixLine = { fg = p.text_strong, bg = p.bg_active_line },
  debugPC = { bg = p.bg_info },
  debugBreakpoint = { fg = p.red },

  -- Menus / popups. Keep focused rows neutral, not Poimandres blue-gray.
  Pmenu = { fg = p.text, bg = p.bg },
  PmenuSel = { fg = p.text_strong, bg = p.bg_menu_selection },
  PmenuKind = { fg = p.blue_soft, bg = p.bg },
  PmenuKindSel = { fg = p.blue_bright, bg = p.bg_menu_selection },
  PmenuExtra = { fg = p.text_muted, bg = p.bg },
  PmenuExtraSel = { fg = p.text, bg = p.bg_menu_selection },
  PmenuMatch = { fg = p.primary, bg = p.bg },
  PmenuMatchSel = { fg = p.primary, bg = p.bg_menu_selection, bold = true },
  PmenuSbar = { bg = p.bg_surface },
  PmenuThumb = { bg = p.text_dim },
  WildMenu = { fg = p.text_strong, bg = p.bg_menu_selection },

  -- Status / tabs ------------------------------------------------------------
  StatusLine = { fg = p.text, bg = p.bg },
  StatusLineNC = { fg = p.text_muted, bg = p.bg },
  TabLine = { fg = p.text_muted, bg = transparent and p.none or p.bg_tab_inactive },
  TabLineFill = { fg = p.text_dim, bg = transparent and p.none or p.bg },
  TabLineSel = { fg = p.text_strong, bg = p.bg_tab_active, bold = true },

  -- Bufferline.nvim. Active buffers need a visible container; the Zed theme's
  -- transparent tabs are pretty, but too subtle inside Neovim.
  BufferLineFill = { bg = transparent and p.none or p.bg },
  BufferLineBackground = { fg = p.text_muted, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineBuffer = { fg = p.text_muted, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineBufferVisible = { fg = p.text, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineBufferSelected = { fg = p.text_strong, bg = p.bg_tab_active, bold = true, italic = true },
  BufferLineNumbers = { fg = p.text_dim, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineNumbersVisible = { fg = p.text_muted, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineNumbersSelected = { fg = p.primary, bg = p.bg_tab_active, bold = true },
  BufferLineCloseButton = { fg = p.text_dim, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineCloseButtonVisible = { fg = p.text_muted, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineCloseButtonSelected = { fg = p.text, bg = p.bg_tab_active },
  BufferLineModified = { fg = p.primary, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineModifiedVisible = { fg = p.primary, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineModifiedSelected = { fg = p.primary, bg = p.bg_tab_active },
  BufferLineDuplicate = { fg = p.text_muted, bg = transparent and p.none or p.bg_tab_inactive, italic = true },
  BufferLineDuplicateVisible = { fg = p.text_muted, bg = transparent and p.none or p.bg_tab_inactive, italic = true },
  BufferLineDuplicateSelected = { fg = p.text_muted, bg = p.bg_tab_active, italic = true },
  BufferLineSeparator = { fg = p.border_dim, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineSeparatorVisible = { fg = p.border_dim, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineSeparatorSelected = { fg = p.primary, bg = p.bg_tab_active },
  BufferLineIndicatorSelected = { fg = p.primary, bg = p.bg_tab_active },
  BufferLineTab = { fg = p.text_muted, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineTabSelected = { fg = p.text_strong, bg = p.bg_tab_active, bold = true },
  BufferLineTabSeparator = { fg = p.border_dim, bg = transparent and p.none or p.bg_tab_inactive },
  BufferLineTabSeparatorSelected = { fg = p.primary, bg = p.bg_tab_active },

  -- Diffs / VCS --------------------------------------------------------------
  DiffAdd = { bg = p.bg_diff_add },
  DiffChange = { bg = p.bg_diff_change },
  DiffDelete = { fg = p.red, bg = p.bg_diff_delete },
  DiffText = { bg = "#31445a" },
  Added = { fg = p.green },
  Changed = { fg = p.blue_bright },
  Removed = { fg = p.red },
  GitSignsAdd = { fg = p.green, bg = normal_bg },
  GitSignsChange = { fg = p.yellow_soft, bg = normal_bg },
  GitSignsDelete = { fg = p.red, bg = normal_bg },
  GitSignsAddNr = { fg = p.green, bg = normal_bg },
  GitSignsChangeNr = { fg = p.yellow_soft, bg = normal_bg },
  GitSignsDeleteNr = { fg = p.red, bg = normal_bg },

  -- Diagnostics --------------------------------------------------------------
  DiagnosticError = { fg = p.red },
  DiagnosticWarn = { fg = p.yellow },
  DiagnosticInfo = { fg = p.blue_bright },
  DiagnosticHint = { fg = p.hint },
  DiagnosticOk = { fg = p.green },
  DiagnosticSignError = { fg = p.red, bg = normal_bg },
  DiagnosticSignWarn = { fg = p.yellow, bg = normal_bg },
  DiagnosticSignInfo = { fg = p.blue_bright, bg = normal_bg },
  DiagnosticSignHint = { fg = p.hint, bg = normal_bg },
  DiagnosticVirtualTextError = { fg = p.red, bg = p.bg_error },
  DiagnosticVirtualTextWarn = { fg = p.yellow, bg = p.bg_warning },
  DiagnosticVirtualTextInfo = { fg = p.blue_bright, bg = p.bg_info },
  DiagnosticVirtualTextHint = { fg = p.hint, bg = p.bg_hint },
  DiagnosticUnderlineError = { sp = p.red, undercurl = true },
  DiagnosticUnderlineWarn = { sp = p.yellow, undercurl = true },
  DiagnosticUnderlineInfo = { sp = p.blue_bright, undercurl = true },
  DiagnosticUnderlineHint = { sp = p.hint, undercurl = true },
  DiagnosticFloatingError = { fg = p.red, bg = p.bg },
  DiagnosticFloatingWarn = { fg = p.yellow, bg = p.bg },
  DiagnosticFloatingInfo = { fg = p.blue_bright, bg = p.bg },
  DiagnosticFloatingHint = { fg = p.hint, bg = p.bg },

  -- LSP references. This replaces the harsh string-focus background.
  LspReferenceText = { bg = p.bg_document_highlight },
  LspReferenceRead = { bg = p.bg_document_highlight },
  LspReferenceWrite = { bg = p.bg_document_highlight },
  LspSignatureActiveParameter = { fg = p.text_strong, bg = p.bg_document_highlight },

  -- Legacy syntax ------------------------------------------------------------
  Comment = { fg = p.text_muted, italic = true },
  Constant = { fg = p.text_strong },
  String = { fg = p.primary },
  Character = { fg = p.primary },
  Number = { fg = p.primary },
  Boolean = { fg = p.primary },
  Float = { fg = p.primary },
  Identifier = { fg = p.text_strong },
  Function = { fg = p.blue_bright },
  Statement = { fg = p.primary },
  Conditional = { fg = p.primary },
  Repeat = { fg = p.primary },
  Label = { fg = p.blue_soft },
  Operator = { fg = p.blue_soft },
  Keyword = { fg = p.primary },
  Exception = { fg = p.red },
  PreProc = { fg = p.blue_soft },
  Include = { fg = p.primary },
  Define = { fg = p.blue_soft },
  Macro = { fg = p.blue_soft },
  PreCondit = { fg = p.blue_soft },
  Type = { fg = p.text },
  StorageClass = { fg = p.blue_soft },
  Structure = { fg = p.blue_soft },
  Typedef = { fg = p.blue_soft },
  Special = { fg = p.blue_soft },
  SpecialChar = { fg = p.primary },
  Tag = { fg = p.primary },
  Delimiter = { fg = p.text },
  SpecialComment = { fg = p.text_muted, italic = true },
  Underlined = { fg = p.primary, underline = true },
  Ignore = { fg = p.text_dim },
  Error = { fg = p.red },
  Todo = { fg = p.yellow, bg = p.bg_warning, bold = true },

  -- Treesitter ---------------------------------------------------------------
  ["@annotation"] = { fg = p.blue_soft, italic = true },
  ["@attribute"] = { fg = p.blue_soft, italic = true },
  ["@boolean"] = { fg = p.primary },
  ["@character"] = { fg = p.primary },
  ["@character.special"] = { fg = p.primary },
  ["@comment"] = { fg = p.text_muted, italic = true },
  ["@comment.documentation"] = { fg = p.text_muted, italic = true },
  ["@constant"] = { fg = p.text_strong },
  ["@constant.builtin"] = { fg = p.red },
  ["@constant.macro"] = { fg = p.blue_soft },
  ["@constructor"] = { fg = p.primary },
  ["@diff.plus"] = { fg = p.green },
  ["@diff.minus"] = { fg = p.red },
  ["@diff.delta"] = { fg = p.yellow_soft },
  ["@function"] = { fg = p.blue_bright },
  ["@function.builtin"] = { fg = p.blue_bright },
  ["@function.call"] = { fg = p.blue_bright },
  ["@function.macro"] = { fg = p.blue_soft },
  ["@keyword"] = { fg = p.primary },
  ["@keyword.conditional"] = { fg = p.primary },
  ["@keyword.coroutine"] = { fg = p.primary },
  ["@keyword.exception"] = { fg = p.red },
  ["@keyword.function"] = { fg = p.primary },
  ["@keyword.import"] = { fg = p.primary },
  ["@keyword.operator"] = { fg = p.primary },
  ["@keyword.repeat"] = { fg = p.primary },
  ["@keyword.return"] = { fg = p.primary },
  ["@label"] = { fg = p.blue_soft },
  ["@markup.heading"] = { fg = p.blue_soft, bold = true },
  ["@markup.italic"] = { fg = p.text_muted, italic = true },
  ["@markup.link"] = { fg = p.primary, underline = true },
  ["@markup.link.label"] = { fg = p.primary },
  ["@markup.link.url"] = { fg = p.primary, underline = true },
  ["@markup.list"] = { fg = p.primary },
  ["@markup.quote"] = { fg = p.text_muted, italic = true },
  ["@markup.raw"] = { fg = p.primary },
  ["@markup.strong"] = { fg = p.text_muted, bold = true },
  ["@module"] = { fg = p.primary },
  ["@namespace"] = { fg = p.primary },
  ["@number"] = { fg = p.primary },
  ["@number.float"] = { fg = p.primary },
  ["@operator"] = { fg = p.blue_soft },
  ["@property"] = { fg = p.white },
  ["@punctuation"] = { fg = p.text },
  ["@punctuation.bracket"] = { fg = p.text },
  ["@punctuation.delimiter"] = { fg = p.text },
  ["@punctuation.special"] = { fg = p.text },
  ["@string"] = { fg = p.primary },
  ["@string.documentation"] = { fg = p.primary },
  ["@string.escape"] = { fg = p.primary },
  ["@string.regexp"] = { fg = p.primary },
  ["@string.special"] = { fg = p.primary },
  ["@string.special.symbol"] = { fg = p.primary },
  ["@tag"] = { fg = p.primary },
  ["@tag.attribute"] = { fg = p.blue_soft, italic = true },
  ["@tag.delimiter"] = { fg = p.text },
  ["@text"] = { fg = p.text },
  ["@text.emphasis"] = { fg = p.text_muted, italic = true },
  ["@text.literal"] = { fg = p.primary },
  ["@text.reference"] = { fg = p.primary },
  ["@text.strong"] = { fg = p.text_muted, bold = true },
  ["@text.title"] = { fg = p.blue_soft },
  ["@text.uri"] = { fg = p.primary, underline = true },
  ["@type"] = { fg = p.text },
  ["@type.builtin"] = { fg = p.text },
  ["@type.definition"] = { fg = p.primary },
  ["@type.interface"] = { fg = p.primary },
  ["@variable"] = { fg = p.text_strong, italic = true },
  ["@variable.builtin"] = { fg = p.primary, italic = true },
  ["@variable.member"] = { fg = p.white },
  ["@variable.parameter"] = { fg = p.text_strong, italic = true },
  ["@variable.parameter.builtin"] = { fg = p.primary, italic = true },

  -- LSP semantic tokens ------------------------------------------------------
  ["@lsp.type.class"] = { link = "@type" },
  ["@lsp.type.comment"] = { link = "@comment" },
  ["@lsp.type.decorator"] = { link = "@attribute" },
  ["@lsp.type.enum"] = { link = "@type" },
  ["@lsp.type.enumMember"] = { link = "@constant" },
  ["@lsp.type.function"] = { link = "@function" },
  ["@lsp.type.interface"] = { link = "@type.interface" },
  ["@lsp.type.keyword"] = { link = "@keyword" },
  ["@lsp.type.macro"] = { link = "@constant.macro" },
  ["@lsp.type.method"] = { link = "@function" },
  ["@lsp.type.namespace"] = { link = "@namespace" },
  ["@lsp.type.number"] = { link = "@number" },
  ["@lsp.type.operator"] = { link = "@operator" },
  ["@lsp.type.parameter"] = { link = "@variable.parameter" },
  ["@lsp.type.property"] = { link = "@property" },
  ["@lsp.type.string"] = { link = "@string" },
  ["@lsp.type.struct"] = { link = "@type" },
  ["@lsp.type.type"] = { link = "@type" },
  ["@lsp.type.typeParameter"] = { link = "@type" },
  ["@lsp.type.variable"] = { link = "@variable" },

  -- Completion ---------------------------------------------------------------
  CmpItemAbbr = { fg = p.text },
  CmpItemAbbrDeprecated = { fg = p.text_dim, strikethrough = true },
  CmpItemAbbrMatch = { fg = p.primary, bold = true },
  CmpItemAbbrMatchFuzzy = { fg = p.primary, bold = true },
  CmpItemKind = { fg = p.blue_soft },
  CmpItemMenu = { fg = p.text_muted },
  CmpGhostText = { fg = p.text_predictive },
  BlinkCmpMenu = { fg = p.text, bg = p.bg },
  BlinkCmpMenuBorder = { fg = p.border, bg = p.bg },
  BlinkCmpMenuSelection = { fg = p.text_strong, bg = p.bg_menu_selection },
  BlinkCmpLabel = { fg = p.text },
  BlinkCmpLabelDeprecated = { fg = p.text_dim, strikethrough = true },
  BlinkCmpLabelMatch = { fg = p.primary, bold = true },
  BlinkCmpKind = { fg = p.blue_soft },
  BlinkCmpSource = { fg = p.text_muted },
  BlinkCmpGhostText = { fg = p.text_predictive },
  BlinkCmpDoc = { fg = p.text, bg = p.bg },
  BlinkCmpDocBorder = { fg = p.border, bg = p.bg },
  BlinkCmpDocCursorLine = { bg = p.bg_active_line },
  BlinkCmpSignatureHelp = { fg = p.text, bg = p.bg },
  BlinkCmpSignatureHelpBorder = { fg = p.border, bg = p.bg },

  -- LazyVim / common plugin surfaces ----------------------------------------
  LazyNormal = { fg = p.text, bg = p.bg },
  LazyButton = { fg = p.text, bg = p.bg_active_line_soft },
  LazyButtonActive = { fg = p.text_strong, bg = p.bg_menu_selection },
  LazyH1 = { fg = p.bg, bg = p.primary, bold = true },
  LazyH2 = { fg = p.blue_bright, bold = true },
  MasonNormal = { fg = p.text, bg = p.bg },
  MasonHeader = { fg = p.bg, bg = p.primary, bold = true },
  MasonHighlight = { fg = p.primary },
  MasonHighlightBlock = { fg = p.bg, bg = p.primary },
  MasonHighlightBlockBold = { fg = p.bg, bg = p.primary, bold = true },

  WhichKey = { fg = p.blue_soft },
  WhichKeyNormal = { fg = p.text, bg = p.bg },
  WhichKeyBorder = { fg = p.border, bg = p.bg },
  WhichKeyTitle = { fg = p.blue_bright, bg = p.bg },
  WhichKeyDesc = { fg = p.text },
  WhichKeyGroup = { fg = p.primary },
  WhichKeySeparator = { fg = p.text_dim },
  WhichKeyValue = { fg = p.text_muted },

  NoiceCmdline = { fg = p.text, bg = p.bg },
  NoiceCmdlinePopup = { fg = p.text, bg = p.bg },
  NoiceCmdlinePopupBorder = { fg = p.border, bg = p.bg },
  NoicePopup = { fg = p.text, bg = p.bg },
  NoicePopupBorder = { fg = p.border, bg = p.bg },
  NoicePopupmenu = { fg = p.text, bg = p.bg },
  NoicePopupmenuBorder = { fg = p.border, bg = p.bg },
  NoicePopupmenuSelected = { fg = p.text_strong, bg = p.bg_menu_selection },
  NoiceConfirm = { fg = p.text, bg = p.bg },
  NoiceConfirmBorder = { fg = p.border, bg = p.bg },

  SnacksNormal = { fg = p.text, bg = p.bg },
  SnacksPicker = { fg = p.text, bg = p.bg },
  SnacksPickerBorder = { fg = p.border, bg = p.bg },
  SnacksPickerTitle = { fg = p.blue_bright, bg = p.bg },
  SnacksPickerInput = { fg = p.text, bg = p.bg },
  SnacksPickerInputBorder = { fg = p.border, bg = p.bg },
  SnacksPickerPrompt = { fg = p.primary, bg = p.bg },
  SnacksPickerMatch = { fg = p.primary, bold = true },
  SnacksPickerList = { fg = p.text, bg = p.bg },
  SnacksPickerListCursorLine = { fg = p.text_strong, bg = p.bg_menu_selection },
  SnacksPickerPreview = { fg = p.text, bg = p.bg },
  SnacksPickerPreviewCursorLine = { bg = p.bg_active_line },
  SnacksPickerDir = { fg = p.text_muted },
  SnacksPickerFile = { fg = p.text },
  SnacksPickerPathHidden = { fg = p.text_dim },
  SnacksPickerPathIgnored = { fg = p.text_dim },
  SnacksDashboardHeader = { fg = p.primary },
  SnacksDashboardDesc = { fg = p.text },
  SnacksDashboardKey = { fg = p.blue_soft },
  SnacksDashboardIcon = { fg = p.primary },
  SnacksDashboardFooter = { fg = p.text_muted },

  NeoTreeNormal = { fg = p.text, bg = normal_bg },
  NeoTreeNormalNC = { fg = p.text, bg = normal_bg },
  NeoTreeEndOfBuffer = { fg = transparent and p.bg or p.bg_surface, bg = normal_bg },
  NeoTreeCursorLine = { bg = p.bg_active_line },
  NeoTreeDirectoryName = { fg = p.text },
  NeoTreeDirectoryIcon = { fg = p.primary },
  NeoTreeFileName = { fg = p.text },
  NeoTreeFileIcon = { fg = p.blue_soft },
  NeoTreeGitAdded = { fg = p.green },
  NeoTreeGitDeleted = { fg = p.red },
  NeoTreeGitModified = { fg = p.yellow_soft },
  NeoTreeGitUntracked = { fg = p.green_soft },
  NeoTreeRootName = { fg = p.blue_bright, bold = true },

  TelescopeNormal = { fg = p.text, bg = p.bg },
  TelescopeBorder = { fg = p.border, bg = p.bg },
  TelescopePromptNormal = { fg = p.text, bg = p.bg },
  TelescopePromptBorder = { fg = p.border, bg = p.bg },
  TelescopePromptPrefix = { fg = p.primary, bg = p.bg },
  TelescopeSelection = { fg = p.text_strong, bg = p.bg_menu_selection },
  TelescopeMatching = { fg = p.primary, bold = true },
  TelescopeTitle = { fg = p.blue_bright, bg = p.bg },

  TroubleNormal = { fg = p.text, bg = p.bg },
  TroubleNormalNC = { fg = p.text, bg = p.bg },
  TroubleCount = { fg = p.primary, bg = p.bg_active_line_soft },
  TroubleText = { fg = p.text },

  MultiCursorCursor = { link = "Cursor" },
  MultiCursorVisual = { link = "Visual" },
  MultiCursorSign = { link = "SignColumn" },
  MultiCursorDisabledCursor = { link = "Visual" },
  MultiCursorDisabledVisual = { link = "Visual" },
  MultiCursorDisabledSign = { link = "SignColumn" },

  MiniIconsAzure = { fg = p.primary },
  MiniIconsBlue = { fg = p.blue_bright },
  MiniIconsCyan = { fg = p.blue_terminal },
  MiniIconsGreen = { fg = p.green },
  MiniIconsGrey = { fg = p.text_muted },
  MiniIconsOrange = { fg = p.orange },
  MiniIconsPurple = { fg = p.purple },
  MiniIconsRed = { fg = p.red },
  MiniIconsYellow = { fg = p.yellow },
}

for group, spec in pairs(groups) do
  hl(group, spec)
end

vim.g.terminal_color_0 = p.bg
vim.g.terminal_color_1 = p.red
vim.g.terminal_color_2 = p.green
vim.g.terminal_color_3 = p.yellow
vim.g.terminal_color_4 = p.blue_terminal
vim.g.terminal_color_5 = p.magenta
vim.g.terminal_color_6 = p.blue_terminal
vim.g.terminal_color_7 = p.white
vim.g.terminal_color_8 = "#73675e"
vim.g.terminal_color_9 = p.red
vim.g.terminal_color_10 = p.green
vim.g.terminal_color_11 = p.yellow
vim.g.terminal_color_12 = p.blue_bright
vim.g.terminal_color_13 = p.magenta
vim.g.terminal_color_14 = p.blue_bright
vim.g.terminal_color_15 = p.white
