theme = "blankeos-zen-dark-blurred"

[editor]
line-number = "relative"
bufferline = "always"

[editor.soft-wrap]
enable = false

[editor.file-picker]
hidden = false
git-ignore = true

[editor.cursor-shape]
normal = "block"
insert = "bar"

# Good shortcuts
[keys.normal.z]
w = ":toggle soft-wrap.enable"

# space-e → toggle yazi sidebar (tmux)
# [keys.normal.space]
# e = ":sh hy-sidebar"

